name: Do update

on:
  schedule:
    - cron: '21 0 * * fri'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Scrape wiki
      run: |
        pipenv run python main.py
        mv output/checksums output/checksums.bak
        mv output/items-drop-sources.json output/items-drop-sources.json.bak
        mv output/items-drop-sources.min.json output/items-drop-sources.min.json.bak
        mv output/items-info.json output/items-info.json.bak
        mv output/items-info.min.json output/items-info.min.json.bak
        mv output/items-production.json output/items-production.json.bak
        mv output/items-production.min.json output/items-production.min.json.bak
        mv output/items-shopitems.json output/items-shopitems.json.bak
        mv output/items-shopitems.min.json output/items-shopitems.min.json.bak
        mv output/items-spawns.json output/items-spawns.json.bak
        mv output/items-spawns.min.json output/items-spawns.min.json.bak
    - name: Run h2-importer
      run: |
        pushd h2-importer
          ./gradlew run --args="../output ../output/data.h2"
        popd
    - name: Generate H2 checksum
      run: |
        sha256sum ./output/data.h2.mv.db > ./output/data.h2.mv.db.sha256.bak
        mv ./output/data.h2.mv.db ./output/data.h2.mv.db.bak
    - name: Copy to target branch
      run: |
        git checkout --force wiki-data
        mv output/checksums.bak output/checksums
        mv output/items-drop-sources.json.bak output/items-drop-sources.json
        mv output/items-drop-sources.min.json.bak output/items-drop-sources.min.json
        mv output/items-info.json.bak output/items-info.json
        mv output/items-info.min.json.bak output/items-info.min.json
        mv output/items-production.json.bak output/items-production.json
        mv output/items-production.min.json.bak output/items-production.min.json
        mv output/items-shopitems.json.bak output/items-shopitems.json
        mv output/items-shopitems.min.json.bak output/items-shopitems.min.json
        mv output/items-spawns.json.bak output/items-spawns.json
        mv output/items-spawns.min.json.bak output/items-spawns.min.json
        mv ./output/data.h2.mv.db.bak ./output/data.h2.mv.db
        mv ./output/data.h2.mv.db.sha256.bak ./output/data.h2.mv.db.sha256
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        add-paths: |
          output/checksums
          output/items-drop-sources.json
          output/items-drop-sources.min.json
          output/items-info.json
          output/items-info.min.json
          output/items-production.json
          output/items-production.min.json
          output/items-shopitems.json
          output/items-shopitems.min.json
          output/items-spawns.json
          output/items-spawns.min.json
        branch: wiki-data-${{ steps.date.outputs.date }}
        base: wiki-data
        title: Wiki scrape data ${{ steps.date.outputs.date }}
        commit-message: Wiki scrape data ${{ steps.date.outputs.date }}
        delete-branch: true
    - name: Display output PR
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
