name: Do update

on:
  schedule:
    - cron: '21 0 * * fri'
  workflow_dispatch:
  push:
    branches:
      - master
      - sqlite

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
    - uses: gradle/gradle-build-action@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv install
    - name: Scrape wiki
      run: |
        pipenv run python main.py
    - name: Run h2-importer
      run: |
        pushd h2-importer
          ./gradlew run --args="../output ../output/data.sqlite"
        popd
    - name: Generate H2 checksum
      run: |
        sha256sum ./output/data.sqlite | cut -d " " -f 1 > ./output/data.sqlite.sha256
    - name: Copy to target branch
      run: |
        git config user.name temp
        git config user.email temp@temp.com
        git checkout -b wiki-data-temp
        git add ./output
        git commit -m "temp data"
        git checkout wiki-data
        git checkout --force wiki-data-temp ./output
        git config --unset user.name
        git config --unset user.email
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
    - uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.PAT }}
        add-paths: |
          output/
        branch: wiki-data-${{ steps.date.outputs.date }}
        base: wiki-data
        title: Wiki scrape data ${{ steps.date.outputs.date }}
        commit-message: Wiki scrape data ${{ steps.date.outputs.date }}
        delete-branch: true
    - name: Display output PR
      if: ${{ steps.cpr.outputs.pull-request-number }}
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
